baseURL: "https://anders-wikum.github.io/" 
title: Anders Wikum
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2

params:
    description: "I am a second-year PhD student in the Operations Research group within the Management Science & Engineering department at Stanford Univeristy."
    author: Anders Wikum
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Anders Wikum
          subtitle: "I am a second-year PhD student in [**Management Science & Engineering**](https://msande.stanford.edu) at Stanford University, fortunate to be advised by 
          [**Ellen Vitercik**.](https://vitercik.github.io) Prior to joining Stanford, I received a B.S. in Operations Research (ORIE) from Cornell University, where I worked with [**David Shmoys**.](https://people.orie.cornell.edu/shmoys/)
          <br><br> My research interests lie at the intersection of machine learning and algorithm design, particually relating to discrete optimization. My work is supported by a [**NDSEG Fellowship**.](https://ndseg.org)"
          imageUrl: "calanques_tightrope.jpeg"
          imageWidth: 175
          imageHeight: 175
          imageTitle: Anders Wikum
          buttons:
            - name: CV
              url: cv.pdf
            - name: Papers
              url: papers/
            # - name: Tags
            #   url: tags/
    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:wikum@stanford.edu
        # - name: Location
        #   url: location/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/anders-wikum

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Anders Wikum"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
